#!/bin/bash
awk '
/app.get\("\/api\/redemptions"/ {
  print "  // API - Admin: Revert team purchase"
  print "  app.post(\"/api/admin/revert-team-purchase\", (req, res) => {"
  print "    const { redemptionId } = req.body;"
  print "    const db = loadDatabase();"
  print "    const redemption = db.teamRedemptions?.find(r => r.id === redemptionId);"
  print "    if (!redemption) return res.status(404).json({ error: \"找不到紀錄\" });"
  print "    const squadUsers = db.users.filter(u => u.team === redemption.team);"
  print "    const costPerMember = Math.round(redemption.cost / (squadUsers.length || 1));"
  print "    squadUsers.forEach(u => u.mapleCoins = (u.mapleCoins || 0) + costPerMember);"
  print "    db.teamRedemptions = db.teamRedemptions?.filter(r => r.id !== redemptionId);"
  print "    saveDatabase(db);"
  print "    res.json({ success: true });"
  print "  });"
  print ""
  print "  // API - Admin: Revert item purchase"
  print "  app.post(\"/api/admin/revert-item-purchase\", (req, res) => {"
  print "    const { redemptionId } = req.body;"
  print "    const db = loadDatabase();"
  print "    const redemption = db.itemRedemptions?.find(r => r.id === redemptionId);"
  print "    if (!redemption) return res.status(404).json({ error: \"找不到紀錄\" });"
  print "    const user = db.users.find(u => u.id === redemption.userId);"
  print "    if (user) {"
  print "      if (user.items) user.items = user.items.filter(id => id !== redemption.itemId);"
  print "      user.mapleCoins = (user.mapleCoins || 0) + redemption.cost;"
  print "      const itemToTypeMap: Record<string, string> = {"
  print "        \"item_0\": \"約訪\","
  print "        \"item_1\": \"成交壽險件\","
  print "        \"item_2\": \"準時出席早會\","
  print "        \"item_3\": \"客戶拜訪\","
  print "        \"item_4\": \"增員活動邀約\","
  print "        \"item_5\": \"遞送建議書\","
  print "        \"item_6\": \"理賠\""
  print "      };"
  print "      const typeAffected = itemToTypeMap[redemption.itemId];"
  print "      let totalPointsReverted = 0;"
  print "      if (typeAffected && db.activities) {"
  print "        for (const act of db.activities) {"
  print "          if (act.userId === user.id && act.type === typeAffected) {"
  print "            const actTime = new Date(act.timestamp).getTime();"
  print "            const redTime = new Date(redemption.timestamp).getTime();"
  print "            if (actTime > redTime) {"
  print "              const rule = ACTIVITY_RULES[typeAffected as ActivityType];"
  print "              const multiplier = Math.max(1, act.count || 1);"
  print "              let basePoints = rule.points * multiplier;"
  print "              if (act.note && act.note.trim().length > 0) basePoints += 5;"
  print "              let boostedPoints = rule.points * multiplier;"
  print "              if (redemption.itemId === \"item_0\") boostedPoints *= 3;"
  print "              if (redemption.itemId === \"item_1\") boostedPoints = Math.ceil(boostedPoints * 1.5);"
  print "              if (redemption.itemId === \"item_5\") boostedPoints = Math.round(boostedPoints * 1.5);"
  print "              if (redemption.itemId === \"item_2\") boostedPoints *= 4;"
  print "              if (redemption.itemId === \"item_3\") boostedPoints *= 2;"
  print "              if (redemption.itemId === \"item_4\") boostedPoints *= 2;"
  print "              if (redemption.itemId === \"item_6\") boostedPoints *= 4;"
  print "              if (act.note && act.note.trim().length > 0) boostedPoints += 5;"
  print "              const difference = boostedPoints - basePoints;"
  print "              act.points -= difference;"
  print "              user.totalScore -= difference;"
  print "              user.mapleCoins -= difference;"
  print "            }"
  print "          }"
  print "        }"
  print "      }"
  print "    }"
  print "    db.itemRedemptions = db.itemRedemptions?.filter(r => r.id !== redemptionId);"
  print "    saveDatabase(db);"
  print "    res.json({ success: true });"
  print "  });"
  print ""
}
{ print }
' server.ts > server.ts.tmp && mv server.ts.tmp server.ts
