#!/bin/bash
awk '
/{activeSubTab === '\''redemptions'\'' && currentUser\?.role === '\''admin'\'' && \(/ {
  print $0
  print "        <div className=\"space-y-8\">"
  print "          {/* 冒險裝備庫 */}"
  print "          <div>"
  print "            <h3 className=\"text-lg font-black text-amber-700 mb-3\">🛡️ 冒險裝備庫紀錄 (個人道具)</h3>"
  print "            <div className=\"border border-slate-100 rounded-2xl overflow-hidden shadow-sm bg-white\">"
  print "              <div className=\"overflow-x-auto max-h-[300px] overflow-y-auto\">"
  print "                <table className=\"w-full text-xs text-left text-slate-600 relative\">"
  print "                  <thead className=\"bg-slate-50 text-[10px] text-slate-400 uppercase font-mono border-b border-slate-100 sticky top-0 z-10 shadow-sm\">"
  print "                    <tr>"
  print "                      <th className=\"px-5 py-3 font-bold\">兌換時間</th>"
  print "                      <th className=\"px-5 py-3 font-bold\">小隊名稱</th>"
  print "                      <th className=\"px-5 py-3 font-bold\">兌換人</th>"
  print "                      <th className=\"px-5 py-3 font-bold\">兌換道具</th>"
  print "                      <th className=\"px-5 py-3 font-bold text-right\">消耗金幣</th>"
  print "                      <th className=\"px-5 py-3 font-bold text-center\">操作</th>"
  print "                    </tr>"
  print "                  </thead>"
  print "                  <tbody className=\"divide-y divide-slate-100 font-sans font-medium\">"
  print "                    {itemRedemptions.length > 0 ? ("
  print "                      itemRedemptions.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()).map(red => ("
  print "                        <tr key={red.id} className=\"hover:bg-slate-50/50 transition-colors\">"
  print "                          <td className=\"px-5 py-4 text-[10px] text-slate-400 font-mono\">"
  print "                            {new Date(red.timestamp).toLocaleString(\"zh-TW\")}"
  print "                          </td>"
  print "                          <td className=\"px-5 py-4\">"
  print "                            <span className=\"px-2.5 py-1 bg-amber-50 text-amber-600 font-black rounded-lg\">"
  print "                              {red.team}"
  print "                            </span>"
  print "                          </td>"
  print "                          <td className=\"px-5 py-4 font-bold text-slate-800\">"
  print "                            {red.realName}"
  print "                          </td>"
  print "                          <td className=\"px-5 py-4 font-bold text-slate-800\">"
  print "                            {red.itemName}"
  print "                          </td>"
  print "                          <td className=\"px-5 py-4 text-right font-mono font-black text-amber-600\">"
  print "                            -{red.cost} 🍁"
  print "                          </td>"
  print "                          <td className=\"px-5 py-4 text-center\">"
  print "                            <button onClick={() => handleRevertItemPurchase(red.id)} className=\"bg-red-50 text-red-600 hover:bg-red-100 px-3 py-1 rounded font-bold transition\">"
  print "                              取消退回"
  print "                            </button>"
  print "                          </td>"
  print "                        </tr>"
  print "                      ))"
  print "                    ) : ("
  print "                      <tr>"
  print "                        <td colSpan={6} className=\"px-5 py-8 text-center text-slate-400\">目前沒有任何道具兌換紀錄！</td>"
  print "                      </tr>"
  print "                    )}"
  print "                  </tbody>"
  print "                </table>"
  print "              </div>"
  print "            </div>"
  print "          </div>"
  print ""
  print "          {/* 邊境補給站 */}"
  print "          <div>"
  print "            <h3 className=\"text-lg font-black text-red-700 mb-3\">☕ 邊境補給站紀錄 (小隊公款)</h3>"
  print "            <div className=\"border border-slate-100 rounded-2xl overflow-hidden shadow-sm bg-white\">"
  print "              <div className=\"overflow-x-auto max-h-[300px] overflow-y-auto\">"
  print "                <table className=\"w-full text-xs text-left text-slate-600 relative\">"
  print "                  <thead className=\"bg-slate-50 text-[10px] text-slate-400 uppercase font-mono border-b border-slate-100 sticky top-0 z-10 shadow-sm\">"
  print "                    <tr>"
  print "                      <th className=\"px-5 py-3 font-bold\">兌換時間</th>"
  print "                      <th className=\"px-5 py-3 font-bold\">小隊名稱</th>"
  print "                      <th className=\"px-5 py-3 font-bold\">兌換人</th>"
  print "                      <th className=\"px-5 py-3 font-bold\">兌換商品</th>"
  print "                      <th className=\"px-5 py-3 font-bold text-right\">消耗金幣</th>"
  print "                      <th className=\"px-5 py-3 font-bold text-center\">操作</th>"
  print "                    </tr>"
  print "                  </thead>"
  print "                  <tbody className=\"divide-y divide-slate-100 font-sans font-medium\">"
  print "                    {teamRedemptions.length > 0 ? ("
  print "                      teamRedemptions.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()).map(red => ("
  print "                        <tr key={red.id} className=\"hover:bg-slate-50/50 transition-colors\">"
  print "                          <td className=\"px-5 py-4 text-[10px] text-slate-400 font-mono\">"
  print "                            {new Date(red.timestamp).toLocaleString(\"zh-TW\")}"
  print "                          </td>"
  print "                          <td className=\"px-5 py-4\">"
  print "                            <span className=\"px-2.5 py-1 bg-red-50 text-red-600 font-black rounded-lg\">"
  print "                              {red.team}"
  print "                            </span>"
  print "                          </td>"
  print "                          <td className=\"px-5 py-4 font-bold text-slate-800\">"
  print "                            {red.captainName}"
  print "                          </td>"
  print "                          <td className=\"px-5 py-4 font-bold text-slate-800\">"
  print "                            {red.reward}"
  print "                          </td>"
  print "                          <td className=\"px-5 py-4 text-right font-mono font-black text-red-600\">"
  print "                            -{red.cost} 💰"
  print "                          </td>"
  print "                          <td className=\"px-5 py-4 text-center\">"
  print "                            <button onClick={() => handleRevertTeamPurchase(red.id)} className=\"bg-red-50 text-red-600 hover:bg-red-100 px-3 py-1 rounded font-bold transition\">"
  print "                              取消退回"
  print "                            </button>"
  print "                          </td>"
  print "                        </tr>"
  print "                      ))"
  print "                    ) : ("
  print "                      <tr>"
  print "                        <td colSpan={6} className=\"px-5 py-8 text-center text-slate-400\">目前沒有任何兌換紀錄！</td>"
  print "                      </tr>"
  print "                    )}"
  print "                  </tbody>"
  print "                </table>"
  print "              </div>"
  print "            </div>"
  print "          </div>"
  print "        </div>"
  print "      )}"
  in_skip = 1
  next
}
in_skip && /^      {\/\* Tab 3: System reset and maintenance \*\// {
  in_skip = 0
  print
  next
}
!in_skip { print }
' src/components/AdminPanel.tsx > src/components/AdminPanel.tsx.tmp && mv src/components/AdminPanel.tsx.tmp src/components/AdminPanel.tsx
